### ISSUE TITLE
Side-by-Side Printing

### ISSUE THREAD

**Issue by Sitrane** [mephitrpg/rpg-cards#11]
Since printing double sided isn't an exact science, even though you have done a great job of lining things up within reason, it would be really nice to be able to print side-by-side and just folder the two halves on top of each other.

Hardcodex.ru added this feature recently and I think your system would greatly benefit from it.

**Comment by stitchlipped** [comment]
Wouldn't the fold itself result in the images being fractionally misaligned anyway?

**Comment by Sitrane** [comment]
That's true, I'm sure it would cause some minor alignment issues.

However, because the cards fronts and backs share the same colors, even if you had to fold the card SLIGHTLY off center to keep it aligned properly, I don't think it would be noticeable since the colors are the same.

I actually made a mockup card and printed it and attached it to this post. 

Ignore the white on the right of the card; Our printer at work uses wax and I didn't really let it cure 100% before I cut and folded.
![img_20141023_105420](https://cloud.githubusercontent.com/assets/9367171/4755788/4f3c1c86-5ac8-11e4-91b7-3cea25f2709f.jpg)
![img_20141023_105438](https://cloud.githubusercontent.com/assets/9367171/4755789/4f425132-5ac8-11e4-85f0-b83711fdebbd.jpg)
![img_20141023_105427](https://cloud.githubusercontent.com/assets/9367171/4755787/4f3b0012-5ac8-11e4-883a-138dc53fba91.jpg)

**Comment by crobi** [comment]
I could add an option for how to arrange the cards on paper (double sided printing, front sides only, side-by-side), it's just not a priority right now. I know double sided printing does not line up perfectly on most printers, however if all cards on a page are the same color, you won't notice it.

If you want to implement this yourself, have a look at the `card_pages_generate_html()` function inside `cards.js`. You'd have to add a function that interleaves elements of `front_cards` and `back_cards`, and add all the UI elements for the corresponding options.

Nice to see cards generated by this project in action, btw!

**Comment by Sitrane** [comment]
Thanks! I already have my 5 spell cards made up for my game Saturday.

I'll have my coder buddy take a look at your code and see if he can tweak it to work; I work with CSS and web design, but this is a bit above me.

Keep up the awesome work!

**Comment by crobi** [comment]
There's an option for customizing the card arrangement now.

Because I'm too lazy to implement it properly, it's limited to one card (front+back) per row, even if you try to stick 4x4 cards on a page (where you could have two cards per row).
