### ISSUE TITLE
Replace .png icons with .svg versions

### ISSUE THREAD

**Issue by Rezenbekk** [mephitrpg/rpg-cards#111]
.png icons are very small which leads to horrible look at larger (3.5"x5.0"+) scales.

Raster images scale pretty badly. Fortunately, the icon pack the author is using has the same icons in SVG. 

Solution is very easy: take the same icon pack but download the .svg version. Then mass replace ".png" to ".svg" in generator/icons.css.

I made it for myself but I'm unable to turn it into a proper pull request for now, sorry.

**Comment by posita** [comment]
~What did you do with the `mogrify` step? Omit it? (If you remember. I know it's been awhile since you filed this.)~ _Yup! After some experimentation, getting rid of it seems appropriate with `.svg`s._

**Comment by posita** [comment]
🙌
