### ISSUE TITLE
Double-sided printing will not work.

### ISSUE THREAD

**Issue by zoabs** [mephitrpg/rpg-cards#114]
When I do double sided printing, the wrong backs are attached to the wrong fronts.

So page 1 for example in print preview it would look like
(Page 1) Front:  A B C
(Page 2) Back: A B C 
However cutting out the cards shows that the front of A ends up with the back of C, B ends up with B, and C ends up with A.

I've tried changing it to 3 x 3 to 3 x 1 to 2 x 2 but either the layout is completely wrong or the above happens. Please help!

**Comment by crobi** [comment]
The back side is generated to be compatible with "flip on long edge" double sided printing. I.e., the position of the cards is flipped horizontally on the back page, like this:
(Page 1) Front: A B C
(Page 2) Back: C B A

This is working as expected for me.

If you see a different order in the generated page, please let me know all of your page settings (from the "Page settings" section on the left).

If you see the above order in the generated page, but the cards don't line up after printing, make sure your printer settings are set to "flip on long edge".
