### ISSUE TITLE
Printing Issue

### ISSUE THREAD

**Issue by samc1992** [mephitrpg/rpg-cards#115]
Hi,
This is not the same as issue #17 .

When I print, i get all the images etc, however, the text on the front is not there.
It'll have the  words in:
section |
Subtitle |
But anything under text | does not appear. Help?

**Comment by crobi** [comment]
Does the text appear on the sample cards?

To load the sample cards, click the "Load sample" button in the top left menu.

**Comment by samc1992** [comment]
Hi,

Yes they do

Sam

On 16 Jun 2018 07:10, Robert Autenrieth <notifications@github.com> wrote:

Does the text appear on the sample cards?

To load the sample cards, click the "Load sample" button in the top left menu.

**Comment by crobi** [comment]
Then the issue is with how you use `text |`. Can you please share the definition of a card that doesn't work?

**Comment by samc1992** [comment]
Hi,

This is one of the cards:

subtitle | Martial Arts
rule
text | When you use the Attack action with an unarmed strike or a monk weapon on your turn, you can make one unarmed strike as a bonus action. For example, if you take the Attack action and attack with a quarterstaff, you can also make an unarmed strike as a bonus action, assuming you haven’t already taken a bonus action this turn.


Sam
________________________________

**Comment by crobi** [comment]
I can't reproduce your issue, the card you posted above works (copy pasting your text into https://crobi.github.io/rpg-cards/generator/generate.html).
