### ISSUE TITLE
Subsection Element Issue

### ISSUE THREAD

**Issue by HustleDragon** [mephitrpg/rpg-cards#116]
**I wish to report a bug.**

**Currently, I see problems with the 'subsection' element. The card identifies said element as "unknown".**

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: Microsoft Windows 10
- Browser: Google Chrome
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: A4
  - Card Size: 2.5" x 3.5" (Poker)
  - Cards/page: 3 x 3
  - Arrangement: Double-sided printing

**I wanted to test the elements before doing my desired cards, problem being the 'subsection' element is not being read and identified as a 'subsection' element. I want the 'subsection' element to work as intended instead of just showing 'Unknown element:'.**

**Comment by crobi** [comment]
There is no `subsection` element, try using `section`.

The documentation is incorrect and should be fixed.

**Comment by henrygab** [comment]
@crobi Can you point me to where in the current repository the source for the [documentation](https://crobi.github.io/rpg-cards/) is?  I'd be happy to submit a pull request to fix this issue.

Thanks!

**Comment by wereHamster** [comment]
@henrygab the [gh-pages](https://github.com/crobi/rpg-cards/tree/gh-pages) branch

**Comment by henrygab** [comment]
@crobi This is now ready, and hopefully I made it trivial for you to review.   Let me know if you have any questions!
