### ISSUE TITLE
Unknown Element

### ISSUE THREAD

**Issue by PapaBear138** [mephitrpg/rpg-cards#118]
Reporting a bug.

Card contents will not print.

Every time I put text into the "Contents" section of a card, it comes up as "Unknown element:" in the preview box.
- OS: Windows 10 Home
- Browser: Microsoft Edge
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: A4
  - Card Size: 2.5" x 3.5" (Poker)
  - Cards/page: 3 x 3
  - Arrangement: Front side only

It should be previewing, and printing, what I type in the "Contents" field.  Am I doing something wrong?  Thank you.

**Comment by HustleDragon** [comment]
Maybe you aren't using a ' | ' between the text and the thing you want to type in (ex. text|This is text).
Maybe I am not understanding the problem at all.

**Comment by henrygab** [comment]
@PapaBear138 Unfortunately, the names are CaSe SenSITive, which isn't clear from the documentation.  Simply ensure you use lower-case for the element name.
