### ISSUE TITLE
Problems updating the icons

### ISSUE THREAD

**Issue by Laucian32** [mephitrpg/rpg-cards#119]
I installed Imagemagick and tried to run the two commands through cmd.exe navigated to the folder but it just puts out an error that "'npm'/'node' is not recognized as an internal or external command, operable program or batch file." Any idea what I'm doing wrong?

**Comment by wereHamster** [comment]
You also need to install [nodejs](https://nodejs.org/en/).

**Comment by Laucian32** [comment]
Alright, got that working but now it's giving me this error:

![what now](https://user-images.githubusercontent.com/42555670/44384101-dc89bd00-a4cf-11e8-8795-e70b311b232f.png)

**Comment by wereHamster** [comment]
It fails while unzipping, my guess is that `http.get` doesn't handle redirects. Can you try changing the URL in the update-icons.js file to start with `https://` instead of `http://`? Line 11 should read:

```
const gameIconsUrl = "https://game-icons.net/archives/png/zip/ffffff/000000/game-icons.net.png.zip";
```

**Comment by Laucian32** [comment]
Still didn't work, so I messed with some stuff and got it working. I'll explain how I did it here so it can help if someone else has this issue:
```
Install Imagemagick https://www.imagemagick.org

Install nodejs https://nodejs.org/en/

Download http://game-icons.net/archives/png/zip/ffffff/000000/game-icons.net.png.zip

Rename it "temp.zip" and put it in the root folder

Edit "update-icons.js" in notepad++ or something doing the following IN ORDER:

	Change line 18 and 19 to:
//const processIconsCmd = "magick mogrify -background white -alpha shape *.png";
const processIconsCmd = `magick mogrify -alpha copy -channel-fx "red=100%, blue=100%, green=100%" *.png`
	Change line 179 to:
.catch(err => console.log("Error", err));
	Delete line 171
	Delete lines 20-36

Run cmd.exe, navigate to the root folder then run the following commands:
	npm install
	node ./resources/tools/update-icons.js
```
Alternatively replace your "update-icons.js" with mine:
[Semi-manual Icon Update.zip](https://github.com/crobi/rpg-cards/files/2308371/Semi-manual.Icon.Update.zip)

**Comment by crobi** [comment]
Thanks @wereHamster for fixing the update icons script!

@Laucian32 could you try again with the fixed script?

**Comment by tontione** [comment]
It doesn't work for me : 

> mogrify.exe: unrecognized option `-channel-fx' @ error/mogrify.c/MogrifyImageCom
mand/4214.

The old line worked for me :
`const processIconsCmd = "mogrify -background white -alpha shape *.png";`

Windows 10 with new nodejs (v8.12.0) & imagemagick (7.0.7) install
