### ISSUE TITLE
description element adding a dot to param1

### ISSUE THREAD

**Issue by PsychoWedge** [mephitrpg/rpg-cards#124]
I don't know if this is a bug or not but I've been playing around with the cards. It's really great overall but I noticed something weird.

So in the documentation it states that property and description do the same thing except that property indents the text. Works and all, but if I use description there is a dot automatically added after param1 that is not added with property. This makes it rather awkward to use if one wants to use it with a colon since it will result in something like "example.:" instead of "example:". I always use a colons after property names and description names because it just looks cleaner to me.

A possible workaround is to just use text and manually make the first words bold but I don't like that so much.

As I said I don't know whether this is a bug or not. If it isn't I'd be happy to edit whatever line I need to edit myself if someone could point me to it. I know how to use an editor but I'm no coder so I don't know what to do without help.

**Comment by granack** [comment]
edit your generator/css/cards.css file to remove or comment the section: 
```
.card-description-name::after {
    content: ".";
}
```
you could even change the . to a : if it's something you want every time you use a description.

Of course you need to be hosting the files on your own server to do that. There are plenty of options to use your computer as a server if you are the only one using it. I personally use python. if you have python installed, open a command line where you save the project files and run 
`python -m http.service 8000`
then open your browser to [http://localhost:8000/generator/generate.html](http://localhost:8000/generator/generate.html)

just for funsies with your own files you can also set the example card set to a set you've saved, so you can reset to your base set anytime with a click of a button (generator/data/card_data_example.js)

**Comment by crobi** [comment]
The initial card elements were inspired by the D&D 5e monster stat block, which uses the current punctuation.

At this point, your best option is probably to define a new card element, or change the existing one in your own copy of the project.

**Comment by mephitrpg** [comment]
New mantained fork https://github.com/crobi/rpg-cards/issues/159
