### ISSUE TITLE
No result after importing a custom json file

### ISSUE THREAD

**Issue by Luxura** [mephitrpg/rpg-cards#126]
**Do you want to request a feature or report a bug?**
A Bug I think

**What is the current behavior?**
When importing this json [https://pastebin.com/k111TYZ0](url) nothing happen ( no notification, no change in th UI, no change in the card list).

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
Importing this [https://pastebin.com/k111TYZ0](url) with the "Load from file option"

- OS: Manjaro 18.0.0 Illyria
- Browser: Firefox 63.0.1,
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: A4
  - Card Size: 2.5"x3.5"
  - Cards/page: 3x3
  - Arrangement: Double sided printing

**What is the expected behavior?**
Loading the json will result in no change

**Comment by wereHamster** [comment]
That is not a valid JSON file. Did you edit it by hand?

**Comment by Luxura** [comment]
I used a python script to generate it from a DataBase them  edit by hand. How can I make it valid ?

**Comment by wereHamster** [comment]
Try https://jsonlint.com/, or https://jsonformatter.curiousconcept.com/, or any of the other options you can find here: https://www.google.ch/search?q=online+json+validator.

**Comment by Luxura** [comment]
Ok thanks
