### ISSUE TITLE
Double Sided Printing Issue

### ISSUE THREAD

**Issue by Sitrane** [mephitrpg/rpg-cards#13]
I was printing out some cards and noticed that the double sided print options is generating with what appears to be a black background?

![2014-11-07 17_23_40-rpg cards](https://cloud.githubusercontent.com/assets/9367171/4961286/c08409de-66cc-11e4-86da-e62c76402345.png)

I am using Google Chrome Version 38.0.2125.111

**Comment by crobi** [comment]
I silently added a feature where the page background of pages containing card backs uses the default color, so that the background is not white if the front and back do not line up perfectly.

You can just set the default color to blue or white in your example.

**Comment by crobi** [comment]
There's a proper option for the page background color now.
