### ISSUE TITLE
Trouble while updating icon

### ISSUE THREAD

**Issue by MScam974** [mephitrpg/rpg-cards#130]
**Do you want to request a feature or report a bug?**
I have an issue while update icon; and i found a solution:

**What is the current behavior?**
win 10, all files needed are installed and the soft is updated

1. Error Error : invalide signature 0x6474683c
I solve by using the following solution : 
>Problems updating icons
>  Laucian32 commented on 22 Aug 2018
> Still didn't work, so I messed with some stuff and got it working. I'll explain how I did it here so it can help if someone else has this issue:
> 
> 
>> Download http://game-icons.net/archives/png/zip/ffffff/000000/game-icons.net.png.zip 
>> Rename it "temp.zip" and put it in the root folder

then i commented the line 20-36 (Download function) and the line 169 (using download function). It worked

2. mogrify wasn't knowned as a command
So i change line 17 

>const processIconsCmd = "mogrify -background white -alpha shape *.png";
to
> const processIconsCmd = "magick mogrify -background white -alpha shape *.png";

magick allow the use of any script

Now i have the new icon transparent.

**Comment by crobi** [comment]
Closing, as the script for updating icons was completely reworked. In particular, it does not depend on Imagemagick anymore. See https://github.com/crobi/rpg-cards#building for new instructions.
