### ISSUE TITLE
The full deck won't generate for printing

### ISSUE THREAD

**Issue by markemoo** [mephitrpg/rpg-cards#132]
**Do you want to request a feature or report a bug?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS:
- Browser:
- Page settings (from the "Page Settings" section of the generator)
  - Page Size:
  - Card Size:
  - Cards/page:
  - Arrangement:

**What is the expected behavior?**

**Comment by markemoo** [comment]
I have completed my deck, but cannot generate the deck for printing.  I get this error code  setImmediate$0.9647194333251399$1

**Comment by Arkonos** [comment]
If you upload our deck I can check if the same happens with my browsers.
Please also add the information requested in your first comment.
