### ISSUE TITLE
Card backs do not print

### ISSUE THREAD

**Issue by uboat50** [mephitrpg/rpg-cards#135]
**Do you want to request a feature or report a bug?**
Report a bug.

**What is the current behavior?**
The back sides of the cards show in the generated window, but do not print.  When I attempt to print a back page, it simply prints blank.

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS:  Windows 7
- Browser:  Mozilla Firefox 68.0.2
- Page settings (from the "Page Settings" section of the generator)
  - Page Size:  US Letter
  - Card Size:  3.5" x 5.0"
  - Cards/page:  2 x 2
  - Arrangement:  Double sided printing

**What is the expected behavior?**
Card backs will print.

**Comment by Arkonos** [comment]
From the FAQ:

> Cards are generated without icons and background colors, what's wrong?
>
> Enable printing backround images in your browser print dialog

Even though the FAQ also claims that Firefox is supported, I had no luck so far printing the backside. Instead of black, there's just nothing in my case though. I use chromium for printing after I'm done, that works.

**Comment by mephitrpg** [comment]
Nowasays it works on Firefox too.

**Comment by mephitrpg** [comment]
Nowadays it works on Firefox too.
