### ISSUE TITLE
Resize text to fit all content

### ISSUE THREAD

**Issue by garrett-woodard** [mephitrpg/rpg-cards#136]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
If the content text is too long, it simply cuts off the card.

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: Windows 10
- Browser: Chrome
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: A4
  - Card Size: 2.5" x 3.5"
  - Cards/page: 3x3
  - Arrangement: Double sided printing

**What is the expected behavior?**
The text should resize smaller to fit all of the content text

**Comment by JeffreyHartman** [comment]
Resizing text is the biggest feature I want with this tool as well. I don't mind if it doesn't auto-resize, but would love a feature to resize the body text similar to the way we can set the title font.

**Comment by mephitrpg** [comment]
New font and page size options were added
