### ISSUE TITLE
Update Routine

### ISSUE THREAD

**Issue by Fetzii** [mephitrpg/rpg-cards#137]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Error Messages

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: Windows 10
- Install the newest versions of Imagemagick and Node.js
- type in "npm install"
[https://www.directupload.net/file/d/5628/o7w7ozr8_png.htm](url)
[https://www.directupload.net/file/d/5628/iwah6qr2_png.htm](url)
-type in "node ./resources/tools/update-icons.js"
[https://www.directupload.net/file/d/5628/piboykof_png.htm](url)

  
**What is the expected behavior?**
Updating the icons without any warnings or error messages

**Comment by Nihilecas** [comment]
I have the same issue and can reproduce @Fetzii observations.

**Comment by TetrisIQ** [comment]
Have a look at [this](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node).

You can use an older version of node to solve this issue

**Comment by Nihilecas** [comment]
@TetrisIQ Downgrading to version 10.19.0 has fixed the first issue.

However, when I use node ./resources/tools/update-icons.js I get 
```
error error: invalid signature: 0x6d74683c
at d:\...\rpg-cards-master\node_modules\unzip\lib\parse.js:59:13
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
```
A quick search points me toward a problem in the unzip module.
I'm afraid this is beyond me. Can anyone help? :)

**Comment by TetrisIQ** [comment]
@Nihilecas I see this issue too. You can download and unzip the files manually and comment out the parts in the node file, so you continue with generating.

**Comment by crobi** [comment]
Closing, as the script for updating icons was completely reworked. In particular, it does not depend on Imagemagick anymore. See https://github.com/crobi/rpg-cards#building for new instructions.
