### ISSUE TITLE
Possibility for italic text

### ISSUE THREAD

**Issue by fbl07** [mephitrpg/rpg-cards#138]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
There is no option for italic text

**What is the expected behavior?**
I think it would great to have an option for italic text (and even maybe other styles). When I make an item card, I often include a flavor-text for the item at the top, then the functionality of the item after that. It would be great to be able to differentiate the 2 by having the flavor-text be in italic.

The way I see this work is to have a content that's the same as the `text` content, but instead using the `italic` content name. This would insert a bloc of text the same way the current `text` content works, but with text in italic.

**Comment by Rykath** [comment]
While it would be convenient to have an `italic` element, you can already use italic text using standard HTML-syntax: `<i>some italic text</i>` similar to how you can use bold text. You can also use other styles using HTML/CSS...

**Comment by fbl07** [comment]
Oh really? Thanks for the information, I did not know that!
