### ISSUE TITLE
Template Support for Creatures

### ISSUE THREAD

**Issue by apoapostolov** [mephitrpg/rpg-cards#139]
Current support for maximum of 7.5" x 5.0" is not enough for printouts for creatures with long properties, and I have recently found this site as a better way to print monsters in a card format than 5etools own Book View format. 

An example of a trunkated creature even using the best format:

![image](https://user-images.githubusercontent.com/4083812/69078745-336aa300-0a41-11ea-9910-117fb5381221.png)

There can be multiple approaches for this
1) Add 7.5" x 7.5" and 7.5" x 10" formats, as this is supported by A4 printing format.
2) Allow the content to flow on a nearby card, creating two cards that cover the same entry. They can be sticking together to be closed like a booklet (the back of the card is used as a cover) 
2) Allow the content to flow on the back of the card, thus creating a two-sided creature card. This is a bit less appealing as it reveals some info when held next to the players, but at the same time the small font doesn't really make it so much recognizable and this is also an option to do that.

**Comment by mephitrpg** [comment]
New mantained fork https://github.com/crobi/rpg-cards/issues/159

**Comment by mephitrpg** [comment]
You can just create two cards, one for the front side and one for the back side, and then print them using the "Front side only" option.
