### ISSUE TITLE
Creating Monster Cards

### ISSUE THREAD

**Issue by Sitrane** [mephitrpg/rpg-cards#14]
I know this isn't exactly what you created these cards to do, but since you have such an AWESOME tool going, it would be really nice if we could use this tool to make Monster Cards.

Now technically, you already can do this, but there are a few improvements that could be made that would really help:
1. I noticed that the white-book icon can have a number overlay; This area would be perfect to put the monsters CR number. Perhaps allow us to just type in a number into the box or allow us to overlay any number over any icon?
2. A good way to enter the stats. Currently I just enter them side by side but they end up using two rows. If it was possible to enter them with the type of stat above and then numbers below, that would be really nice.
3. Monsters tend to have A LOT of stuff you need to enter, so it would be nice to be able to enter information on the backs of the cards and just lose the image backing.

Below is what I was able to currently enter based on the amount of space I had.

![2014-11-10 10_55_15-rpg cards](https://cloud.githubusercontent.com/assets/9367171/4978723/03d2a99e-68f2-11e4-936c-6cefb20416f8.png)

P.S. This is a personally created and released monster created my Andrew Kropff and I am using it only as an example.

**Comment by Sitrane** [comment]
Optimized the card slightly more, but even then, we can see that a simple Goblin is really maximizing the amount of space possible.

![goblincard](https://cloud.githubusercontent.com/assets/9367171/4979202/6c34113c-68f5-11e4-8fd9-5105557d64a4.png)

Again, this is a freely available monster and in no way shape or form my own creation nor will I provide the JSON file for replicating; Except to the creator of said program should he desire it.

**Comment by crobi** [comment]
Personally, I use 3.5" x 5" cards for monsters (you can put 4 of those on a sheet of paper), as there simply isn't enough space on a 2.5" x 3.5" card. Putting text on the back on the card is a feature I am unlikely to implement any time soon - if you feel it is important, please open a separate ticket for it. There is also an undocumented feature you could use: `dndstats | 14 | 11 | 13 | 1 | 3 | 1` will output a stat block as shown below.

![card](https://cloud.githubusercontent.com/assets/577871/4988704/befc2c90-696a-11e4-9132-4366ad163000.png)

**Comment by crobi** [comment]
As for the number overlay, this is related to [this issue](https://github.com/crobi/rpg-cards/issues/15). As number overlays do not work with all icons, and the optimal position and size of the number depends on the icon, I am unlikely to implement this. In any case, if you have further input on this feature, please add it to the above issue.

If you want to create icons with numbers manually, I have used [Inkscape](https://inkscape.org/en/), which is a free and open source vector graphics editor.

**Comment by Sitrane** [comment]
Thanks for the information on the dndstats, that is AWESOME! When will that be pushed out to the live preview online?

I downloaded the files, but when I generate the cards, they appear to be generating very strangely. I can see the one card I created, but it's in the middle of the two pages and then there are pure white cards being generated all over.

Also, I had a feeling that may be the case with the icons. Perhaps I'll mess around with it myself.

If I create anything I think everyone could benefit from, how would I go about submitting them to you?

Thanks again!

**Comment by crobi** [comment]
I don't update the live preview too often, as it requires some work. So you'll have to wait a couple of days.

How did you set up your page? For the 3.5" x 5" cards, I use A4 paper (or Letter), 2x2 cards per page, and double-sided printing. The tool sometimes generates blank cards to fill the page, so that cards line up when printing double-sided.

If you want to contribute to this project, the easiest way is the [github way](https://guides.github.com/activities/forking/) - fork the project, do something with your copy of the project, and then send me a pull request.

**Comment by Sitrane** [comment]
I was using US Letter but I forgot to set it to 2x2; It was still set to 3x3, which caused issues. Thanks for the reply.

I'm not much of one for GitHub, so I'll consult my coder friend and if I design anything, I'll be sure to create a fork and let you know.

Thanks for all the awesome work!

**Comment by crobi** [comment]
The live preview supports `dndstats` now
