### ISSUE TITLE
Is there a Card limit

### ISSUE THREAD

**Issue by adin267** [mephitrpg/rpg-cards#140]
[rpg_card.zip](https://github.com/crobi/rpg-cards/files/3900804/rpg_card.zip)
Hey trying to import these cards into the generator, is there a limit to how many cards can be imported into the generater because when i try samples of 1, 20 and 50 it all goes smoothly but once I go above 100 it just won't import. This code was generated through a vba script I made based on card descriptions imported from 5etools so everything should be spookum. (my only other thought is that a card in there is causing an error) but yeh anywho

**Comment by alice-cash** [comment]
You need to escape double-quotes. On line 2019, you have the following:

>       "text | By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range, such as a squirrel, a blue jay, or a bat. You specify a location, which you must have visited, and a recipient who matches a general description, such as "a man or woman dressed in the uniform of the town guard" or "a red-haired dwarf wearing a pointed hat." You also speak a message of up to twenty-five words. The target beast travels for the duration of the spell toward the specified location, covering about 50 miles per 24 hours for a flying messenger, or 25 miles for other animals.When the messenger arrives, it delivers your message to the creature that you described, replicating the sound of your voice. The messenger speaks only to a creature matching the description you gave. If the messenger doesn't reach its destination before the spell ends, the message is lost, and the beast makes its way back to where you cast this spell.",

It is breaking on the 
> such as "a man or woman dressed in the uniform of the town guard" or "a red-haired dwarf wearing a pointed hat."

e.g. it needs to be 
> such as \\"a man or woman dressed in the uniform of the town guard\\" or \\"a red-haired dwarf wearing a pointed hat.\\"

**Comment by crobi** [comment]
Closing, as it doesn't look like a bug in the generator.
