### ISSUE TITLE
Freeze when selecting icons

### ISSUE THREAD

**Issue by Dasagriva** [mephitrpg/rpg-cards#143]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Creating a new card, when selecting some (but not all) icons, the browser freezes. With "all-seeing-eye" it freezes; with "crenulated shield" it works. 

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: kubuntu 18.04
- Browser: Chrome
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: A4
  - Card Size: Poker
  - Cards/page: 3x3
  - Arrangement: Double side
Using the icons as per the download, no update

**What is the expected behavior?**

**Comment by crobi** [comment]
Does it freeze completely, or just for a second? After rpg-cards switched to SVG icons, typing the icon name got a bit laggier, as it takes longer to load and render all those SVG icons in the dropdown.

**Comment by Dasagriva** [comment]
It freezes completely, and I waited several minutes in some cases.

**Comment by Nihilecas** [comment]
It works for me with "all-seeing-eye" as well as with other icons. I have noticed some lag as crobi described, but no freeze.
OS: Windows 10 Pro
Browser: Firefox
I ran the "Building" commands prior to use from the command line. Maybe this will fix your problem.

Edit: It works in Chrome for me as well.

**Comment by crobi** [comment]
I'm using Chrome on macOS, never seen a freeze either.

@Dasagriva are you running your own web site, or are you using https://rpg-cards.vercel.app/?

**Comment by Dasagriva** [comment]
I’m running my own on kubuntu and Chrome

**Comment by Dasagriva** [comment]
I will try the building commands, I am away from the computer right now,
but iirc I needed to install some additional software to run that process,
so I skipped it. As I understand it, I only needed it if I updated the icons

**Comment by crobi** [comment]
> iirc I needed to install some additional software to run that process, so I skipped it. As I understand it, I only needed it if I updated the icons

The build command changed recently. It doesn't require any extra software anymore, but it is now required. Without it, you won't see any icons.

**Comment by Dasagriva** [comment]
Ok, good to know. I have not checked the updates lately. Thank you for
letting me know

**Comment by Dasagriva** [comment]
Updated as per the instructions, and even though is not as frequent as before, still happens. Can make 3 cards, not more

**Comment by mephitrpg** [comment]
do you still have this problem? I can't reproduce it.

**Comment by Dasagriva** [comment]
I’m not using it much nowadays, but I don’t remember happening much the
last times I used it
