### ISSUE TITLE
Allow numbers in header after icon 

### ISSUE THREAD

**Issue by Raisins** [mephitrpg/rpg-cards#15]
Would be useful to show icon then number in the header.  

Example:
[this is my title     icon number]

Dagger of stabbing        [image of dagger] 4

**Comment by crobi** [comment]
I am unlikely to implement this feature, as I want to keep the project simple and don't want to provide extensive layout customization options.

If you want to implement this yourself, append `<span style="float:right">4</span>` to your title and inside the `css/card.css` file, modify `.card-title-inlineicon-container` by changing `right: -1mm` to `right: 3mm`

**Comment by crobi** [comment]
Can you try http://crobi.github.io/rpg-cards/generator-next/generate.html (load the sample and enter a number in the icon text field)? Is this what you had in mind?

**Comment by Raisins** [comment]
@crobi Awesome :+1:

**Comment by 123jrf** [comment]
How would I implement this in my downloaded version? I'd like to be able to change the number on a card-by-card basis like you can on the online test version (or whatever it is), not just have a static number there.
