### ISSUE TITLE
icons.css missing from /generator/css/

### ISSUE THREAD

**Issue by Mathizsias** [mephitrpg/rpg-cards#155]
I'd love to host a mirror of this app on my private server and IIS is reporting the following.

2020-07-14 11:07:11 ::1 GET /rpg-cards/css/icons.css - 443 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/83.0.4103.116+Safari/537.36+Edg/83.0.478.64 https://localhost/rpg-cards/ 404 0 2 0

/rpg-cards/css/icons.css does indeed nog exist withing the folder structure.

**Comment by crobi** [comment]
@Mathizsias Did you follow the build instructions (https://github.com/crobi/rpg-cards#building)?

**Comment by Mathizsias** [comment]
Well, no, since it makes no sense to me what to do there. All I understand in this context is that the css file is missing.

Steps 1, 2 and 3 are in an unclear context for me, if you could expand, then please. 👍

**Comment by crobi** [comment]
> Steps 1, 2 and 3 are in an unclear context for me, if you could expand, then please.

Did you try following the steps one at a time? Is there anything particular you did not understand?

**Step 1: "Check out this repository"**

If you don't know how Git and GitHub repositories work, I would suggest reading a tutorial such as [this one](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository).

**Step 2: Make sure you have Node installed**

I have added this step to make it clear you need to have [Node.js](https://nodejs.org/) installed.

**Step 3: "Run npm install"**

Open a command line, change to the directory to where you have cloned the repository, and type `npm install`

**Step 4: "Run npm run build"**

In the same command line, type `npm run build"`.

**Comment by mephitrpg** [comment]
New mantained fork https://github.com/crobi/rpg-cards/issues/159
