### ISSUE TITLE
5.0 x 7.5

### ISSUE THREAD

**Issue by Gwynndows98** [mephitrpg/rpg-cards#156]
**Do you want to request a feature or report a bug?**

Request a Feature

**What is the current behavior?**

Currently, only Landscape 7.5 x 5.0 is the only available orientation in that size

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**

**What is the expected behavior?**

It would be awesome if we could have this large sized card in Portrait!

**Comment by mephitrpg** [comment]
New mantained fork https://github.com/crobi/rpg-cards/issues/159
