### ISSUE TITLE
Section Spacing and Property Tags

### ISSUE THREAD

**Issue by Sitrane** [mephitrpg/rpg-cards#16]
I noticed while creating a section that is you then use a "property" tag without having a "fill", the section will overlap the property tags text slightly.

It would be nice to either add a small amount of spacing underneath the section tag OR allow the "fill" modifier to be used between two section tags; Basically it will center between the tags instead of the whole page.

**Comment by crobi** [comment]
The space below a "section" is not handled properly, I should fix the CSS. It works for "description", but not for "property".

The "fill" tag can already be used center between tags - if you have two "fill | 1" tags, they should have exactly the same height.

**Comment by LMOlivera** [comment]
@crobi I am doing some clean up of the repository. I see that this bug is over 9 years old and does not seem to be happening anymore and I will close the issue.

@Sitrane if this is still wrong, please reopen it.
