### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by Shaantera** [mephitrpg/rpg-cards#160]
report a bug

**What is the current behavior?** cards are not lining up on the pages correctly
![RPG cards](https://user-images.githubusercontent.com/87839257/126727949-fd9453d9-c20c-4cc2-a394-7aeebf63c94c.jpeg)

**Comment by mephitrpg** [comment]
New mantained fork #159

**Comment by RacecarNoises** [comment]
I'm having the same issue; when I generate the preview the cards get laid our correctly for two rows, then a column down the middle goes off the page. I've replicated the issue from the .json file on two computers.

**Comment by mephitrpg** [comment]
can you be more specific? I can't replicate the bug.

**Comment by mephitrpg** [comment]
I can't replicate the bug.
