### ISSUE TITLE
Formating of generator

### ISSUE THREAD

**Issue by AmberBullough** [mephitrpg/rpg-cards#165]
**Do you want to request a feature or report a bug?**
Bug
**What is the current behavior?**

When attempting to generate cards to print, they line up vertically rather than side by side for the front, but the back is fine. 
**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: BigSur
- Browser:Chrome
- Page settings (from the "Page Settings" section of the generator)
  - Page Size:
  - Card Size:
  - Cards/page:
  - Arrangement:

**What is the expected behavior?**

**Comment by mephitrpg** [comment]
New mantained fork #159
