### ISSUE TITLE
More Text Space

### ISSUE THREAD

**Issue by kenseikai1** [mephitrpg/rpg-cards#166]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
when importing and creating cards, there is not enough space to get all the text i would like to fit in
 could an option to be presented to continue text onto the back of the cards, instead of just an icon?

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS:
- Browser:
- Page settings (from the "Page Settings" section of the generator)
  - Page Size:
  - Card Size:
  - Cards/page:
  - Arrangement:

**What is the expected behavior?**

**Comment by mephitrpg** [comment]
New mantained fork #159

**Comment by mephitrpg** [comment]
#139

**Comment by mephitrpg** [comment]
You can just create two cards, one for the front side and one for the back side, and then print them using the "Front side only" option.
