### ISSUE TITLE
Printing issues

### ISSUE THREAD

**Issue by rhammill** [mephitrpg/rpg-cards#17]
They aren't printing properly, either from Chrome or IE. The banner color and icons don't print. Instead it's just a border with a square border where the icon should be. The title text is in gray. If I could eliminate the square border and change the title text color they would work fine.

Otherwise I like the design better than any other cards out there right now.

Thanks.

Randy

**Comment by rhammill** [comment]
Just tried Firefox too. Incognito mode, no addins, etc. Also tried running as administrator. I'll try on a different machine when I have a chance.

Randy

**Comment by crobi** [comment]
Enable printing of background colors and images. I should put this in the help text.

**Comment by rhammill** [comment]
Thanks!
