### ISSUE TITLE
[Feature request] Add game-icons badges as card icons

### ISSUE THREAD

**Issue by PozoLetras** [mephitrpg/rpg-cards#170]
**Feature request**
The game icons webpage has some extra icons that are use in said web as badges [https://game-icons.net/badges.html](url). However, it would be interesting to have them as icons for the cards because they add more variety and are circular. Specially the numbered badges can be useful for indicating creature CR (limited from 0-9, but at least it's something) or spell level more clearly.

**Comment by mephitrpg** [comment]
Remembrer that HTML is allowed. In example, you can write something like this:
````
text | Pay <img src="https://game-icons.net/badges/number-3.svg" style="height:1em"> to destroy target creature.
````
to get this:

![image](https://github.com/crobi/rpg-cards/assets/2466456/5891a827-0bf7-4656-b48e-e526db5aaa92)

so you're not limited to icons provided from this app.
