### ISSUE TITLE
Printed single cards with Poker card size do not fill up page

### ISSUE THREAD

**Issue by squidgy617** [mephitrpg/rpg-cards#171]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
When attempting to print (to PDF specifically, not sure if this impacts real printers) a single card per-page using with the page size at standard poker card size, the cards do not fill up the entire page, instead only a tiny portion of it. Older versions of the program filled up the whole page properly.

![image](https://user-images.githubusercontent.com/25260326/215637041-f64abd15-40b1-4274-bd5f-aaa114a90440.png)

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: Windows 10
- Browser: Google Chrome/Firefox/Microsoft Edge
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: 2.5" x 3.5"
  - Card Size: Poker - 2.5" x 3.5"
  - Cards/page: 1
  - Arrangement: Front side only

**What is the expected behavior?**
Cards in older versions would fill up the page preview and thus print properly when printing to a PDF. Something in the newer versions must have broken this functionality.

This is a preview from an older version:
![image](https://user-images.githubusercontent.com/25260326/215637326-281c4ba8-d169-4fb6-b695-2199bb215ece.png)

**Comment by kregkz** [comment]
I also encountered this. I wanted a single card per page. I set custom page sizes to match card size but ran into what you see on firefox. On chrome, I got white space around the cards. My work around was to use firefox, print to pdf, then use a pdf editor (pdfill tools) to crop the pdf page size down to the card size I wanted.

**Comment by mephitrpg** [comment]
To obtain the desired behavior should be sufficient to set the card dimensions equal to those of the page, or use the Zoom setting in the Page tab. Could be ok for you?

**Comment by squidgy617** [comment]
That didn't appear to be working before, but oddly enough it seems fine now. This can probably be closed. Thank you!
