### ISSUE TITLE
Card Font Size does not work

### ISSUE THREAD

**Issue by ArthOfCode** [mephitrpg/rpg-cards#172]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

Changing "Card Font Size" does nothing.

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: Windows 11
- Browser: Firefox / Chrome / Edge
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: A4
  - Card Size: Standard, Poker
  - Cards/page: 3x3
  - Arrangement: Double side printing

**What is the expected behavior?**

It should change font size for specific card.

**Comment by mephitrpg** [comment]
should be ok now, can you confirm? thanks
