### ISSUE TITLE
generating output at letter size produces A4 size page.

### ISSUE THREAD

**Issue by lycanthropejeff** [mephitrpg/rpg-cards#174]
B**ug Report

Selecting 'US Letter' Size output does not change the output size which is causing the scale of the cards to be off.**

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: **Windows 10, 64-bit**
- Browser: **Chrome** 
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: **US Letter**
  - Card Size: **2.5 X 3.5**
  - Cards/page: **3x3**
  - Arrangement: **Portrait, curved corners**

**What is the expected behavior?**

**for the output to be US letter size (8.5"x11") instead of A4 size.**

Thank you very much for a great tool and your time.

**Comment by mephitrpg** [comment]
should be ok now, can you confirm? thanks
