### ISSUE TITLE
Generated page does not save correctly

### ISSUE THREAD

**Issue by olegmykhailenko** [mephitrpg/rpg-cards#175]
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**
After successfully generating a page I use Print in browser to save document as pdf, but pdf is saved without icons. Also when I save html and reopen it from file icons are gone too. 

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: Windows 10
- Browser: 
[RPG cards.pdf](https://github.com/crobi/rpg-cards/files/11792641/RPG.cards.pdf)
Google Chrome and Microsoft Edge
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: A4
  - Card Size: standard
  - Cards/page: 3x3
  - Arrangement: Double sided print
All page settings are default, didn`t touch any

**What is the expected behavior?**
File is saved correctly.

**Comment by supauch** [comment]
I have a checkbox when I go to print that says "background graphics" if that is unchecked then I don't get the icons or the backgrounds.

**Comment by mephitrpg** [comment]
@olegmykhailenko do you confirm that the solution suggested by @supauch works for you?

**Comment by olegmykhailenko** [comment]
Yes, tried it again and @supauch 's advice helped. Thanks!
