### ISSUE TITLE
Printing first page only

### ISSUE THREAD

**Issue by Conspiracy3015** [mephitrpg/rpg-cards#18]
After creating the output file, it will only print the first page. Even a print preview only shows the first page.

**Comment by crobi** [comment]
Works for me on both firefox and chrome. How many cards does your deck contain? And did you enter your own cards? Because the sample dataset only contains exacly one page of cards.

**Comment by Conspiracy3015** [comment]
Even the sample data set only prints the first page. I'm using Firefox 33.1.1.
My own deck only has 24 cards at the moment.

**Comment by crobi** [comment]
You're right, now I can reproduce it as well. This appears to be a bug in Firefox (see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=258397#c23)). Workaround, as per the bug report: select all (CTRL+A), then in the print dialog, use "selection" as the print range. Alternatively, use Chrome.
