### ISSUE TITLE
Incorrect printing template BUG

### ISSUE THREAD

**Issue by LinoHawken** [mephitrpg/rpg-cards#182]
I don't know exacly what happened, but when I whent to see how were my cards doing and see them in the printing page, they were all disorganized, one on top of the other, caos

I have no idea what's causing it or how to solve it
![image](https://github.com/crobi/rpg-cards/assets/157893663/c7b34c35-0024-4afa-88d6-c82f20327a03)

**Comment by mephitrpg** [comment]
Please, can you send a ascreenshot of your settings?

Note that there aren't sophisticated checks that ensure to keep a solid print layout: if you don't set perfect measures, the result could be a mess.

**Comment by mephitrpg** [comment]
does it still happen?

**Comment by KIMMES1999** [comment]
<img width="954" alt="Screenshot rpg-cards BUG" src="https://github.com/crobi/rpg-cards/assets/170718397/aaf15ff5-c922-4438-86a1-50cab9a156a2">

[RPG cards BUG.pdf](https://github.com/crobi/rpg-cards/files/15431454/RPG.cards.BUG.pdf)

[Loot_Magic Items.json](https://github.com/crobi/rpg-cards/files/15431456/Loot_Magic.Items.json)

[Loot_Treasures.json](https://github.com/crobi/rpg-cards/files/15431457/Loot_Treasures.json)


I have the same problem. When trying to generate my magic item cards, the template is all messed up.
But if I "load from file" my treasure cards and generate without changing anything, the cards generate just fine.
There seems to be a problem with my magic items file specifically.
I have attached both my treasure & magic items files (for comparison), a screenshot of my generate settings, and the generated pdf file of the messed up template.

Edit: I also just notice that all the magic item cards came out cursive after generating, while that should also not be the case and doesn't happen with the treasure cards.

**Comment by mephitrpg** [comment]
it happens because you wrote invalid HTML. In example, you didn't close the `<i>` tag on the last row of Amethyst Lodestone and other cards.

**Comment by KIMMES1999** [comment]
Ahhh that might do it. 
I”ll try that out soon. 
Didn’t think it would be a problem to keep an <i> open but that sounds logical. 
Thanks for the help.
