### ISSUE TITLE
Problem when generating cards for printing - missing css/class-icons.css

### ISSUE THREAD

**Issue by Rushino** [mephitrpg/rpg-cards#187]
Hello,

The generator seem to have a missing css named css/class-icons.css. When i click generate, i see the cards for a second then "object object" appear on the screen. If you check in the console, it seem there a missing CSS not on the server.

**Comment by raitocan** [comment]
Hey! I'm having the same issue! have you tried to execute the project locally?

**Comment by Rushino** [comment]
Yup it seem to work once you build it locally.

Thank you!

**Comment by syntroniks** [comment]
https://github.com/crobi/rpg-cards/blob/e449f5559d9940df795bd21fc52ec6defbd293e3/generator/output.html#L26 should be removed

maybe https://github.com/crobi/rpg-cards/commit/bef3e2740d52d751c7d7b7081c56241a1ed5965d got reverted at some point? Picking that commit may fix things

**Comment by syntroniks** [comment]
Disabling react dev tools actually fixed this for me.

**Comment by mephitrpg** [comment]
I removed the unused css link.

I fixed the [Object object] text in output.html too. Now a "Close" button appairs if the render fails or if you reload the page.

Thanks for your feedback!
