### ISSUE TITLE
Cannot Print Icons

### ISSUE THREAD

**Issue by aspirito2015** [mephitrpg/rpg-cards#19]
For some reason my printer just isn't printing the icons for my cards (in the top right and on the back) or the gradient on the back. All I do is hit "Generate", go to the new tab, right click, and hit print. Am I messing something up? Is it my printer? I doubt the program's bugged or anything. Thanks in advance.

**Comment by crobi** [comment]
Duplicate of #17 - you need to enable printing background colors and images in the print preview. 

I should put this in the help text.

**Comment by crobi** [comment]
Print help text updated.
