### ISSUE TITLE
New version prints on US Letter incorrectly. Older version works fine.

### ISSUE THREAD

**Issue by bryanjmccoy** [mephitrpg/rpg-cards#191]
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**
When attempting to print on US Letter, the spacing for gets messed up on the current version. My local version from march 18th 2024 does not have this issue and spaces the cards correctly.

The page with the cards seems to generate correctly, but when sending to print or send to PDF, the formatting gets messed up. 

Again, i would have said this was an issue with my printer, but it works fine on the old version.

**If the current behavior is a bug, please provide the steps to reproduce, along with the following information:**
- OS: windows
- Browser: chrome or firefox
- Page settings (from the "Page Settings" section of the generator)
  - Page Size: US Letter
  - Card Size: 2.5 inch by 3.5 inch
  - Cards/page: 9
  - Arrangement: 3x 3

**What is the expected behavior?**

generated cards
![image](https://github.com/crobi/rpg-cards/assets/13629575/a97416ee-183e-45ab-ac90-46d4c02a27f4)

printed cards
![image](https://github.com/crobi/rpg-cards/assets/13629575/16e89c95-312c-4f50-aad0-31d2e9d28c3b)

**Comment by mephitrpg** [comment]
Just pushed a fix, let me know. Thanks for the feedback!

**Comment by bryanjmccoy** [comment]
Prints work again for me. Thanks!
