### ISSUE TITLE
Unable to Add Contents

### ISSUE THREAD

**Issue by wjhamel** [mephitrpg/rpg-cards#26]
When trying to add text to the contents on a new card, it simply displays "Unknown element:", rather than desired text.
![screen shot 2015-03-04 at 9 49 44 pm](https://cloud.githubusercontent.com/assets/11324684/6498286/6771f066-c2b8-11e4-9e82-c1740d55189e.png)

**Comment by crobi** [comment]
"Unknown element:" should be produced if you use an invalid definition of the contents. Can you share your source data, or a screenshot of how you defined the contents?

**Comment by wjhamel** [comment]
I might simply be confused. Is there a way to enter contents in plaintext, rather than code?

**Comment by crobi** [comment]
No. Try prefixing your plaintext with `text |`. For example, if you want to add a single line of text saying "Example content", enter the following:

```
text | Example content
```

**Comment by wjhamel** [comment]
Thanks so much! It's all set now
