### ISSUE TITLE
Save as jpg?

### ISSUE THREAD

**Issue by ryantheleach** [mephitrpg/rpg-cards#27]
Any change of saving each page as a jpg?

It would help greatly for table top simulator, then we can just generate 10 across and 7 down image templates that will load straight into the game.

**Comment by crobi** [comment]
This was mentioned in #25:

There are ways to export a JPG from inside HTML/JavaScript ([here](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas) or [here](https://github.com/niklasvh/html2canvas)), but those sound very shaky I'm not sure it will work well.

If you have a tool that can convert PDF to JPG (there's tons of those online), try the following: Export your deck with a custom page size equal to your card size. This way each page in the PDF contains one card without any borders. Then, export each PDF page to an image.
