### ISSUE TITLE
Script for updating icons from game-icons

### ISSUE THREAD

**Issue by crobi** [mephitrpg/rpg-cards#39]
game-icons.net keeps adding new icons every couple of days. This project needs an automated script that extracts at least the list of icon names, so that issues like #38 don't appear to users.

**Comment by d-ferente** [comment]
Any news about this? any chance of a version with the option for upload the icon or use an url?

**Comment by crobi** [comment]
I didn't have time to work on this recently, and the next big step would be to rewrite the whole project (see #36). So if you need custom/new icons, these are your best options:
- post a pull request with updated icons (download the zip from game-icons.net and then use a script from [here](https://github.com/crobi/rpg-cards/tree/web-components/resources/scripts) to move all the icons)
- read https://github.com/crobi/rpg-cards/issues/33 for how to hack this project to include arbitrary URLs

**Comment by garylzimmer** [comment]
I have all the new icons in one directory, with them white on transparent, but not sure what next to do...

**Comment by crobi** [comment]
I have added a script for updating icons from game-icons.net. The usage is described in the readme.
