### ISSUE TITLE
Card generation

### ISSUE THREAD

**Issue by Ranzer1255** [mephitrpg/rpg-cards#42]
there is an issue when trying to generate cards any size other than poker or bridge. they seem to overlap and start before the "page"

screenshots: 

![screenshot 2015-10-19 20 16 42](https://cloud.githubusercontent.com/assets/5742529/10595657/5b098928-76a0-11e5-9678-759fda01f42c.png)
![screenshot 2015-10-19 20 34 24](https://cloud.githubusercontent.com/assets/5742529/10595702/d7fe0cd8-76a0-11e5-8685-9a15461060a9.png)

**Comment by crobi** [comment]
What page size did you choose (A4/Letter)? And what cards/page setting (3x3 cards)? You have to manually enter how many cards per page you want to have, if you have larger cards, try putting 2x2 cards on a page.

Automatically computing how many cards to put on a page is something that I want to implement in the far future, but for now you have to enter this manually.

**Comment by Ranzer1255** [comment]
ah ha! I must be completely blind i never saw the card per page adjustment option.... I apologize for the confusion.
