### ISSUE TITLE
Update the list of available icons

### ISSUE THREAD

**Issue by DesktopMan** [mephitrpg/rpg-cards#52]
There are a lot more available from the website now. I tried to do this myself, but it doesn't look like the way of doing so and the scripts required are all here. E.g. I did not find the script to generate the css for the icons, nor merging in the custom icons not from game-icons.net.

**Comment by crobi** [comment]
I did it manually using a command that lists all files in a directory and some regex replace (see [this folder](https://github.com/crobi/rpg-cards/tree/master/resources/tools)). If you want to have a shot at it, you can also have a look at [this folder in a branch](https://github.com/crobi/rpg-cards/tree/web-components/resources/scripts), which contains more scripts that might help. You'll also need [mogrify](http://www.imagemagick.org/script/mogrify.php) to transform white-on-black images to white-on-transparent ones.

Unfortunately I won't have time to work on this in the near future, but if you post a PR then I'll update the live site.

For adding a script to update the icons, there's already #39.
