### ISSUE TITLE
Generate without Card Backs

### ISSUE THREAD

**Issue by 123jrf** [mephitrpg/rpg-cards#63]
I want to generate and print my cards without the card backs on them (I don't really want them, so printing them would be a waste of expensive ink). I know I can set the printer up to only print specific pages, in this case the ones that have the card fronts on them, but for a lot of pages this is a pain. Is there anyway I can generate a PDF without the backs at all?

**Comment by crobi** [comment]
There's a setting for this: Page settings -> Arrangement -> Front side only
