### ISSUE TITLE
Large Cards won't Generate Properly

### ISSUE THREAD

**Issue by 123jrf** [mephitrpg/rpg-cards#64]
When I go to generate a 3.5x5.0 card, it comes out a funky. The paper has wierd cuts in it, the card front isn't there, and the card back is halfway between two pages.

**Comment by crobi** [comment]
You're probably trying to fit too many cards on a page. Unfortunately, you have to set this up manually (this should be improved in a future version). Try to use the following setting: Page setting -> Cards/page -> 2 x 2
