### ISSUE TITLE
Use LocalStorage for data persistence

### ISSUE THREAD

**Issue by sedge** [mephitrpg/rpg-cards#65]
Web storage APIs have come really far, so I thought I'd take a swing at making this tool save directly to your browser. It requires a modern browser, but otherwise should work everywhere. It should also make autosaving (#28) really easy.

I'll probably implement this one way or another on my fork since I frequently use this awesome tool. If there's interest then I'll post a PR 👍

**Comment by crobi** [comment]
👍 A PR would definitely be welcome!

**Comment by crobi** [comment]
PR #67 is now merged and deployed. Note that it only auto-saves when you change the active card.
