### ISSUE TITLE
Generation Not Working

### ISSUE THREAD

**Issue by g8shouse** [mephitrpg/rpg-cards#69]
It looks like the generate button is not working correctly. I'm not sure how to fix it but it brings up the cards in strange places on the page so that all of the work I did putting in the info for my cards is useless.

**Comment by wereHamster** [comment]
Can you attach a screenshot? Also, which browser are you using?

**Comment by g8shouse** [comment]
Not sure if you can open this but here is what it generated and here are
some screen shots in case that doesn't work. Thank. I tried Chrome,
Firefox, and Edge.

_Alexander Gates_
_Owner - G8S LLC_
_www.g8shouse.com http://www.g8shouse.com_
_385-444-3487_

**Comment by wereHamster** [comment]
Unfortunately you can't upload attachments via email, you'll have to attach the images via the github web interface.

**Comment by g8shouse** [comment]
Here are the screenshots.

![screen shot 1](https://cloud.githubusercontent.com/assets/22221642/20357458/4edafc24-abe5-11e6-90f7-332586002560.png)
![screen shot 3](https://cloud.githubusercontent.com/assets/22221642/20357467/569e3f3e-abe5-11e6-9a7c-f556088768e0.png)

**Comment by crobi** [comment]
> I'm not sure how to fix it but it brings up the cards in strange places on the page

What card size did you use, and how many cards per page did you choose? If you select 3x3 cards per page with 3.5"x5" sized cards, the cards won't fit on the page and the output will look broken.

**Comment by crobi** [comment]
No response, I'm assuming the issue was solved by choosing the correct card size

**Comment by ghost** [comment]
I had the same issue and it was due to using the `<small>` tag without properly closing it at the end of each card. 

I also found out that using html elements inline within the card text may causes issues like this with the generator.

Edit: I know crobi just closed this thread, but I thought my input would be helpful here.
