### ISSUE TITLE
Allow to multiple info on the same line

### ISSUE THREAD

**Issue by ghost** [mephitrpg/rpg-cards#72]
Hello,

I'm trying to use this to make a few monster cards, one thing that I noticed that could help a bit was the possibility to put "AC", "Hit Points" and "Speed" on the same line but I wasn't able to do so without breaking the card structure.

Stay classy!

**Comment by crobi** [comment]
This is a fairly specific request. Could you work around using either of the following?

`property | | <b>AC</b>: 10, <b>HP</b>: 60, <b>Speed</b>: 30ft`

`property | Properties | AC 10, HP 60, Speed 30ft`

**Comment by ghost** [comment]
Well, that works! Thanks!
