### ISSUE TITLE
Rules not spacing correctly with 2 line subtitle

### ISSUE THREAD

**Issue by samvbeckmann** [mephitrpg/rpg-cards#80]
Placing a rule below a 2 line subtitle does not properly lower the rule another line.
<img width="269" alt="screen shot 2017-01-31 at 16 18 30" src="https://cloud.githubusercontent.com/assets/8978312/22487006/52e26abe-e7d1-11e6-9da5-07a8181e116f.png">

```
subtitle | Wondrous item, uncommon (requires attunement)
rule
```

**Comment by ghost** [comment]
How are you writing it?
Try:

```
subtitle | Woundrous item, uncommom
subtitle | (requires attunement)
rule
```

**Comment by samvbeckmann** [comment]
Ah, that works as expected. But should multi-line subtitles be supported with only one subtitle tag?

**Comment by crobi** [comment]
Looks like a problem with the CSS. Feel free to fix it and post a PR!

**Comment by samvbeckmann** [comment]
I know it's been two years, but stumbled upon this again and decided to fix it. Seems to work fine just removing the fixed height tag, and allowing line-height to manage height.

https://github.com/crobi/rpg-cards/pull/128
