### ISSUE TITLE
Some icons wont work

### ISSUE THREAD

**Issue by machandler** [mephitrpg/rpg-cards#81]
Some icons in the built in icon thing don't work, such as http://game-icons.net/skoll/originals/spiked-bat.html
If you could fix this in the future that would be great.

**Comment by crobi** [comment]
> Some icons in the built in icon thing don't work

Can you please provide more details?

If you see some icons on rpg-icons that do not exist in this generator, then see #39 und #38 (icons are only imported from rpg-icons every few months)

**Comment by machandler** [comment]
Quite a few icons that I see in gameicons don’t work in the web rpg card builder. I wanted to know how to fix this because I/m making some cards and the icons are pretty important.

**Comment by crobi** [comment]
If you need this fast, see [this comment](https://github.com/crobi/rpg-cards/issues/39#issuecomment-147230776) for some details on how to fix this.

Otherwise, wait until I update the icons (might take a while).

**Comment by machandler** [comment]
Thanks

**Comment by crobi** [comment]
I have updated the icons from game-icons.net and added a script for automatically updating them (see readme).

**Comment by machandler** [comment]
Great! Keep ut the good work
