### ISSUE TITLE
Generation Errors

### ISSUE THREAD

**Issue by baaabuuu** [mephitrpg/rpg-cards#87]
I have tried created a few spell cards for one of my players, however, when I would try it would bug like this. 

3x3 generating error
![image](https://cloud.githubusercontent.com/assets/19477331/25736761/2b2ce296-3174-11e7-8ea9-3df983958710.png)
2x2 generating error
![image](https://cloud.githubusercontent.com/assets/19477331/25736769/3d6d8d5c-3174-11e7-827c-251b543903a1.png)
2x2 error if you try to add an extra image to "fill" 
![image](https://cloud.githubusercontent.com/assets/19477331/25736793/654c6bcc-3174-11e7-8bf9-9a316bf7797e.png)

**Comment by crobi** [comment]
I can't reproduce this on Chrome, Firefox, or Safari. Can you please specify:
- Which browser you use, including browser version
- What card size you chose in the generator (e.g. 2.5"x3.5")
- What page size you chose in the generator (e.g., A4)
- What card layout you chose in the generator (e.g., 3x3 cards per page)

**Comment by baaabuuu** [comment]
I tried using Chrome and Edge getting the same error.
Chrome version: Version 58.0.3029.96 (64-bit)
Presets are:
![image](https://cloud.githubusercontent.com/assets/19477331/25771134/380506d0-3249-11e7-8b27-f7588394d033.png)


My file is attached here if you want a look at it.

https://www.mediafire.com/?kdekpo14o6mdze5

**Comment by crobi** [comment]
Works for me with the file you attached. Te file contains the sample cards however, not the ones from your screenshots. Does the error appear with the sample cards for you?

Also, are the screenshots with the bugged layout from the page that opens when you click "generate", or from the browser print preview dialog when you try to print?

The only thing I can reproduce is the strange layout if you select a 2x2 (or 2x3) layout. The cards don't overflow, but are arranged in 3 instead of 2 columns.

**Comment by baaabuuu** [comment]
Sorry, that I accidently uploaded the wrong file.

No your sample file is not causing errors, I've been busy with an exam.

The screenshots with the bugged layout appear when I click the browser print dialog and whenever I click generate.
![image](https://cloud.githubusercontent.com/assets/19477331/25824954/5fdb3036-3441-11e7-9c5b-60ef4df5c7b2.png)

Also if I try to print the icons disappear.


https://www.mediafire.com/?5bwk3lkvm76w8ng

**Comment by baaabuuu** [comment]
Edit, I just figured it out.

It is due to Hex( in the file) being too long making it fudge up.

**Comment by wereHamster** [comment]
@baaabuuu the problem is that you have a typo in the third card (Hellish Rebuke), the `<b>` tag around `half` is not properly closed:

```
takes <b>2d10 fire damage</b> on a <b>failed save</b>, or <b>half<b> as much damage on a <b>successful</b> one.
```

–> `<b>half<b>` needs to be `<b>half</b>`!

And it looks like you have the same mistake in a later card, too.
