### ISSUE TITLE
Saving files does not work on IE

### ISSUE THREAD

**Issue by checkyboy** [mephitrpg/rpg-cards#89]
Hi everyone -- whenever I try to save a file, it can't be found locally later -- I'm using Windows 10 / IE 11.  I've tried a straight test.json name as well as c:\games\test.json and .\test.json.  

Any suggestions?

**Comment by crobi** [comment]
First of all: The editor does not save the file to the given location (web sites can't write to the local file system), it just downloads the file. The only thing you can customize is the file name, the browser usually saves the file to the download folder.

That being said, downloading the file is broken on IE. Please consider using a non-outdated browser (Chrome, Firefox, or Edge).

Downloading files on IE could be solved by using [this IE-specific API](https://stackoverflow.com/questions/18755750/saving-text-in-a-local-file-in-internet-explorer-10/20927897#20927897).

**Comment by mephitrpg** [comment]
Internet Explorer is not supported anymore
