### ISSUE TITLE
Add Card for Actions/Abilities

### ISSUE THREAD

**Issue by stecya** [mephitrpg/rpg-cards#9]
Add Card for Abilities with resources (ex. Wild Shape or Superiority Dices . )
Those abilities should contain empty squares or circles
Something like this https://sketch.io/render/sketch544660f73223a.png

**Comment by crobi** [comment]
Not sure what you are requesting... what are you going to put into those circles/squares? Do you want to cross them out each time a player uses the ability?

**Comment by stecya** [comment]
That's right

**Comment by crobi** [comment]
There's a new feature now - use `boxes | 3 | 2` to add a line with 3 boxes, each of them of size 2 (where size 1 is the size of the letter "e").

The feature is now active in the master branch, I will update the project page soon.

**Comment by stecya** [comment]
Nice, Thank you
