### ISSUE TITLE
Generate Not Working

### ISSUE THREAD

**Issue by mustardman523** [mephitrpg/rpg-cards#94]
When I click Generate, another tab comes up like it should, and I see the output cards for a split second. But almost immediately the page becomes completely blank except for the text "[object Object]" in the upper-left side of the page. Do you know why this could be, or how I can fix it?

Thanks!

**Comment by crobi** [comment]
Works for me in Chrome, Firefox, and Safari. Which browser are you using? And have you tried disabling any plugins?

**Comment by mustardman523** [comment]
I had not, and what do you know, but the very first plugin I block did the trick. It was Goodblock Ad Blocker. I thought simply turning it off for the website was enough, but clearly it wasn't. It's working just fine now, thank you.
